### ISSUE TITLE
fix tests to not need environment variables so that circle can run successfully on forks

### ISSUE THREAD

**Issue by meara** [minifast/conference-opportunities#6]
For PRs from forks, circle builds will fail with `KeyError: key not found: "TWITTER_CONSUMER_KEY"`.
Example build: https://circleci.com/gh/minifast/conference-opportunities/131

Apparently environment variables are not available on forks for security reasons:
https://circleci.com/docs/fork-pr-builds/

The test suite needs to not depend on environment variables so that circle builds will be possible for PRs from forks.

**Comment by ohrite** [comment]
Hi @meara!

This is an awesome observation, and @cczona told me all about what happened here.  Is this still happening for you?

**Comment by ohrite** [comment]
@meara After https://github.com/conference-opportunities/conference-opportunities/pull/10 by @sarahmei, I think this might be resolved. Sound good? 😄

**Comment by ohrite** [comment]
Closing for now!
