### ISSUE TITLE
Duplicate twitterwidget element on conference page

### ISSUE THREAD

**Issue by AnnieH** [minifast/conference-opportunities#7]
Test failure: https://github.com/minifast/conference-opportunities/blob/master/spec/features/view_a_conference_spec.rb#L18

Expected behavior: 1 'twitterwidget' element that contains a tweet.

Actual behavior: 2 html 'twitterwidget' elements on the page exist with the same id 'twitter-widget-0' and other properties. The first one is empty while the second one contains an actual tweet,

**Comment by ohrite** [comment]
Hi @AnnieH!

We made a bunch of changes around authentication that may address this issue.  Is it still happening for you?

**Comment by ohrite** [comment]
Hi @AnnieH!  I think this is closable after https://github.com/conference-opportunities/conference-opportunities/pull/10 was resolved.  Thanks so much!
